"""Add new field to Device

Revision ID: 485c01e13ef3
Revises: 
Create Date: 2026-03-08 20:44:10.534219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "485c01e13ef3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "device",
        sa.Column("idle_timeout", sa.Integer(), nullable=False, server_default="1200"),
    )
    op.add_column(
        "device",
        sa.Column("idle_power", sa.Float(), nullable=False, server_default="2.0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device", "idle_power")
    op.drop_column("device", "idle_timeout")
    op.drop_column("device", "description")
    # ### end Alembic commands ###
